// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from game.proto</summary>
public static partial class GameReflection {

  #region Descriptor
  /// <summary>File descriptor for game.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpnYW1lLnByb3RvIkUKDkdldEdhbWVJbmZvUmVxEg8KB3Jvb21faWQYASAB",
          "KAkSEQoJZ2FtZV90eXBlGAIgASgFEg8KB2NvbW1hbmQYAyABKAUiZgoOR2V0",
          "R2FtZUluZm9Sc3ASDwoHcmV0Y29kZRgBIAEoBRIMCgRybXNnGAIgASgJEhEK",
          "CWdhbWVfaW5mbxgDIAEoCRIRCglnYW1lX3R5cGUYBCABKAUSDwoHY29tbWFu",
          "ZBgFIAEoBSJHCg9TZW5kR2FtZURhdGFSZXESDwoHcm9vbV9pZBgBIAEoCRIQ",
          "CghyZXFfdHlwZRgCIAEoBRIRCglnYW1lX2RhdGEYAyABKAkiVQoPU2VuZEdh",
          "bWVEYXRhUnNwEg8KB3JldGNvZGUYASABKAUSDAoEcm1zZxgCIAEoCRIQCghy",
          "ZXFfdHlwZRgDIAEoBRIRCglnYW1lX2RhdGEYBCABKAkiMgoLU2VuZEdhbWVC",
          "c3QSEAoIcmVxX3R5cGUYAyABKAUSEQoJZ2FtZV9kYXRhGAQgASgJKlUKElNl",
          "bmRHYW1lQnN0UmVxVHlwZRILCgdJTlZBTElEEAASCwoHUFZQX01TRxABEg0K",
          "CVBWUF9MT1NFUhACEhYKEkdsb2JhbF9MZWFkZXJib2FyZBADKkIKEkdldEdh",
          "bWVJbmZvQ29tbWFuZBIVChFHRVRfUFZQX0dBTUVfSU5GTxAAEhUKEEdFVF9Q",
          "TEFZRVJfQkxPT0QQ6QdCMlowZ2l0aHViLmNvbS9idWQtdGVjaG5vbG9naWVz",
          "L2VuZ2luZS1wcm90b2NvbC9nYW1lYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SendGameBstReqType), typeof(global::GetGameInfoCommand), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGameInfoReq), global::GetGameInfoReq.Parser, new[]{ "RoomId", "GameType", "Command" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGameInfoRsp), global::GetGameInfoRsp.Parser, new[]{ "Retcode", "Rmsg", "GameInfo", "GameType", "Command" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SendGameDataReq), global::SendGameDataReq.Parser, new[]{ "RoomId", "ReqType", "GameData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SendGameDataRsp), global::SendGameDataRsp.Parser, new[]{ "Retcode", "Rmsg", "ReqType", "GameData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SendGameBst), global::SendGameBst.Parser, new[]{ "ReqType", "GameData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum SendGameBstReqType {
  /// <summary>
  //// 无效
  /// </summary>
  [pbr::OriginalName("INVALID")] Invalid = 0,
  /// <summary>
  ////
  /// </summary>
  [pbr::OriginalName("PVP_MSG")] PvpMsg = 1,
  /// <summary>
  //// 出局玩家
  /// </summary>
  [pbr::OriginalName("PVP_LOSER")] PvpLoser = 2,
  /// <summary>
  //// 全局排行榜
  /// </summary>
  [pbr::OriginalName("Global_Leaderboard")] GlobalLeaderboard = 3,
}

public enum GetGameInfoCommand {
  /// <summary>
  //// 兼容，获取PVP游戏信息
  /// </summary>
  [pbr::OriginalName("GET_PVP_GAME_INFO")] GetPvpGameInfo = 0,
  /// <summary>
  //// 获取玩家生命值
  /// </summary>
  [pbr::OriginalName("GET_PLAYER_BLOOD")] GetPlayerBlood = 1001,
}

#endregion

#region Messages
public sealed partial class GetGameInfoReq : pb::IMessage<GetGameInfoReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetGameInfoReq> _parser = new pb::MessageParser<GetGameInfoReq>(() => new GetGameInfoReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetGameInfoReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGameInfoReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGameInfoReq(GetGameInfoReq other) : this() {
    roomId_ = other.roomId_;
    gameType_ = other.gameType_;
    command_ = other.command_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGameInfoReq Clone() {
    return new GetGameInfoReq(this);
  }

  /// <summary>Field number for the "room_id" field.</summary>
  public const int RoomIdFieldNumber = 1;
  private string roomId_ = "";
  /// <summary>
  //// [rm-sdk-para] 房间ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RoomId {
    get { return roomId_; }
    set {
      roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "game_type" field.</summary>
  public const int GameTypeFieldNumber = 2;
  private int gameType_;
  /// <summary>
  //// 游戏类型 1 - pvp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GameType {
    get { return gameType_; }
    set {
      gameType_ = value;
    }
  }

  /// <summary>Field number for the "command" field.</summary>
  public const int CommandFieldNumber = 3;
  private int command_;
  /// <summary>
  //// 具体命令
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Command {
    get { return command_; }
    set {
      command_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetGameInfoReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetGameInfoReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoomId != other.RoomId) return false;
    if (GameType != other.GameType) return false;
    if (Command != other.Command) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
    if (GameType != 0) hash ^= GameType.GetHashCode();
    if (Command != 0) hash ^= Command.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RoomId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(RoomId);
    }
    if (GameType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(GameType);
    }
    if (Command != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Command);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RoomId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(RoomId);
    }
    if (GameType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(GameType);
    }
    if (Command != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Command);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RoomId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
    }
    if (GameType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameType);
    }
    if (Command != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Command);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetGameInfoReq other) {
    if (other == null) {
      return;
    }
    if (other.RoomId.Length != 0) {
      RoomId = other.RoomId;
    }
    if (other.GameType != 0) {
      GameType = other.GameType;
    }
    if (other.Command != 0) {
      Command = other.Command;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          RoomId = input.ReadString();
          break;
        }
        case 16: {
          GameType = input.ReadInt32();
          break;
        }
        case 24: {
          Command = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          RoomId = input.ReadString();
          break;
        }
        case 16: {
          GameType = input.ReadInt32();
          break;
        }
        case 24: {
          Command = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class GetGameInfoRsp : pb::IMessage<GetGameInfoRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetGameInfoRsp> _parser = new pb::MessageParser<GetGameInfoRsp>(() => new GetGameInfoRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetGameInfoRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGameInfoRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGameInfoRsp(GetGameInfoRsp other) : this() {
    retcode_ = other.retcode_;
    rmsg_ = other.rmsg_;
    gameInfo_ = other.gameInfo_;
    gameType_ = other.gameType_;
    command_ = other.command_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGameInfoRsp Clone() {
    return new GetGameInfoRsp(this);
  }

  /// <summary>Field number for the "retcode" field.</summary>
  public const int RetcodeFieldNumber = 1;
  private int retcode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Retcode {
    get { return retcode_; }
    set {
      retcode_ = value;
    }
  }

  /// <summary>Field number for the "rmsg" field.</summary>
  public const int RmsgFieldNumber = 2;
  private string rmsg_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Rmsg {
    get { return rmsg_; }
    set {
      rmsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "game_info" field.</summary>
  public const int GameInfoFieldNumber = 3;
  private string gameInfo_ = "";
  /// <summary>
  //// json 序列化后的游戏数据数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameInfo {
    get { return gameInfo_; }
    set {
      gameInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "game_type" field.</summary>
  public const int GameTypeFieldNumber = 4;
  private int gameType_;
  /// <summary>
  //// 游戏类型 1 - pvp
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GameType {
    get { return gameType_; }
    set {
      gameType_ = value;
    }
  }

  /// <summary>Field number for the "command" field.</summary>
  public const int CommandFieldNumber = 5;
  private int command_;
  /// <summary>
  //// 具体命令
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Command {
    get { return command_; }
    set {
      command_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetGameInfoRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetGameInfoRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Retcode != other.Retcode) return false;
    if (Rmsg != other.Rmsg) return false;
    if (GameInfo != other.GameInfo) return false;
    if (GameType != other.GameType) return false;
    if (Command != other.Command) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Retcode != 0) hash ^= Retcode.GetHashCode();
    if (Rmsg.Length != 0) hash ^= Rmsg.GetHashCode();
    if (GameInfo.Length != 0) hash ^= GameInfo.GetHashCode();
    if (GameType != 0) hash ^= GameType.GetHashCode();
    if (Command != 0) hash ^= Command.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Retcode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Retcode);
    }
    if (Rmsg.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Rmsg);
    }
    if (GameInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(GameInfo);
    }
    if (GameType != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(GameType);
    }
    if (Command != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Command);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Retcode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Retcode);
    }
    if (Rmsg.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Rmsg);
    }
    if (GameInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(GameInfo);
    }
    if (GameType != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(GameType);
    }
    if (Command != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Command);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Retcode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
    }
    if (Rmsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Rmsg);
    }
    if (GameInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameInfo);
    }
    if (GameType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameType);
    }
    if (Command != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Command);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetGameInfoRsp other) {
    if (other == null) {
      return;
    }
    if (other.Retcode != 0) {
      Retcode = other.Retcode;
    }
    if (other.Rmsg.Length != 0) {
      Rmsg = other.Rmsg;
    }
    if (other.GameInfo.Length != 0) {
      GameInfo = other.GameInfo;
    }
    if (other.GameType != 0) {
      GameType = other.GameType;
    }
    if (other.Command != 0) {
      Command = other.Command;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Retcode = input.ReadInt32();
          break;
        }
        case 18: {
          Rmsg = input.ReadString();
          break;
        }
        case 26: {
          GameInfo = input.ReadString();
          break;
        }
        case 32: {
          GameType = input.ReadInt32();
          break;
        }
        case 40: {
          Command = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Retcode = input.ReadInt32();
          break;
        }
        case 18: {
          Rmsg = input.ReadString();
          break;
        }
        case 26: {
          GameInfo = input.ReadString();
          break;
        }
        case 32: {
          GameType = input.ReadInt32();
          break;
        }
        case 40: {
          Command = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SendGameDataReq : pb::IMessage<SendGameDataReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SendGameDataReq> _parser = new pb::MessageParser<SendGameDataReq>(() => new SendGameDataReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SendGameDataReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameDataReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameDataReq(SendGameDataReq other) : this() {
    roomId_ = other.roomId_;
    reqType_ = other.reqType_;
    gameData_ = other.gameData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameDataReq Clone() {
    return new SendGameDataReq(this);
  }

  /// <summary>Field number for the "room_id" field.</summary>
  public const int RoomIdFieldNumber = 1;
  private string roomId_ = "";
  /// <summary>
  //// [rm-sdk-para] 房间ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RoomId {
    get { return roomId_; }
    set {
      roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "req_type" field.</summary>
  public const int ReqTypeFieldNumber = 2;
  private int reqType_;
  /// <summary>
  //// 请求类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ReqType {
    get { return reqType_; }
    set {
      reqType_ = value;
    }
  }

  /// <summary>Field number for the "game_data" field.</summary>
  public const int GameDataFieldNumber = 3;
  private string gameData_ = "";
  /// <summary>
  //// 序列化的游戏数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameData {
    get { return gameData_; }
    set {
      gameData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SendGameDataReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SendGameDataReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoomId != other.RoomId) return false;
    if (ReqType != other.ReqType) return false;
    if (GameData != other.GameData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
    if (ReqType != 0) hash ^= ReqType.GetHashCode();
    if (GameData.Length != 0) hash ^= GameData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RoomId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(RoomId);
    }
    if (ReqType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ReqType);
    }
    if (GameData.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RoomId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(RoomId);
    }
    if (ReqType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ReqType);
    }
    if (GameData.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RoomId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
    }
    if (ReqType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReqType);
    }
    if (GameData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SendGameDataReq other) {
    if (other == null) {
      return;
    }
    if (other.RoomId.Length != 0) {
      RoomId = other.RoomId;
    }
    if (other.ReqType != 0) {
      ReqType = other.ReqType;
    }
    if (other.GameData.Length != 0) {
      GameData = other.GameData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          RoomId = input.ReadString();
          break;
        }
        case 16: {
          ReqType = input.ReadInt32();
          break;
        }
        case 26: {
          GameData = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          RoomId = input.ReadString();
          break;
        }
        case 16: {
          ReqType = input.ReadInt32();
          break;
        }
        case 26: {
          GameData = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SendGameDataRsp : pb::IMessage<SendGameDataRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SendGameDataRsp> _parser = new pb::MessageParser<SendGameDataRsp>(() => new SendGameDataRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SendGameDataRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameDataRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameDataRsp(SendGameDataRsp other) : this() {
    retcode_ = other.retcode_;
    rmsg_ = other.rmsg_;
    reqType_ = other.reqType_;
    gameData_ = other.gameData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameDataRsp Clone() {
    return new SendGameDataRsp(this);
  }

  /// <summary>Field number for the "retcode" field.</summary>
  public const int RetcodeFieldNumber = 1;
  private int retcode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Retcode {
    get { return retcode_; }
    set {
      retcode_ = value;
    }
  }

  /// <summary>Field number for the "rmsg" field.</summary>
  public const int RmsgFieldNumber = 2;
  private string rmsg_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Rmsg {
    get { return rmsg_; }
    set {
      rmsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "req_type" field.</summary>
  public const int ReqTypeFieldNumber = 3;
  private int reqType_;
  /// <summary>
  //// 请求类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ReqType {
    get { return reqType_; }
    set {
      reqType_ = value;
    }
  }

  /// <summary>Field number for the "game_data" field.</summary>
  public const int GameDataFieldNumber = 4;
  private string gameData_ = "";
  /// <summary>
  //// 序列化的游戏数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameData {
    get { return gameData_; }
    set {
      gameData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SendGameDataRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SendGameDataRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Retcode != other.Retcode) return false;
    if (Rmsg != other.Rmsg) return false;
    if (ReqType != other.ReqType) return false;
    if (GameData != other.GameData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Retcode != 0) hash ^= Retcode.GetHashCode();
    if (Rmsg.Length != 0) hash ^= Rmsg.GetHashCode();
    if (ReqType != 0) hash ^= ReqType.GetHashCode();
    if (GameData.Length != 0) hash ^= GameData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Retcode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Retcode);
    }
    if (Rmsg.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Rmsg);
    }
    if (ReqType != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ReqType);
    }
    if (GameData.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Retcode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Retcode);
    }
    if (Rmsg.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Rmsg);
    }
    if (ReqType != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ReqType);
    }
    if (GameData.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Retcode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
    }
    if (Rmsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Rmsg);
    }
    if (ReqType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReqType);
    }
    if (GameData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SendGameDataRsp other) {
    if (other == null) {
      return;
    }
    if (other.Retcode != 0) {
      Retcode = other.Retcode;
    }
    if (other.Rmsg.Length != 0) {
      Rmsg = other.Rmsg;
    }
    if (other.ReqType != 0) {
      ReqType = other.ReqType;
    }
    if (other.GameData.Length != 0) {
      GameData = other.GameData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Retcode = input.ReadInt32();
          break;
        }
        case 18: {
          Rmsg = input.ReadString();
          break;
        }
        case 24: {
          ReqType = input.ReadInt32();
          break;
        }
        case 34: {
          GameData = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Retcode = input.ReadInt32();
          break;
        }
        case 18: {
          Rmsg = input.ReadString();
          break;
        }
        case 24: {
          ReqType = input.ReadInt32();
          break;
        }
        case 34: {
          GameData = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SendGameBst : pb::IMessage<SendGameBst>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SendGameBst> _parser = new pb::MessageParser<SendGameBst>(() => new SendGameBst());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SendGameBst> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameBst() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameBst(SendGameBst other) : this() {
    reqType_ = other.reqType_;
    gameData_ = other.gameData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SendGameBst Clone() {
    return new SendGameBst(this);
  }

  /// <summary>Field number for the "req_type" field.</summary>
  public const int ReqTypeFieldNumber = 3;
  private int reqType_;
  /// <summary>
  //// 请求类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ReqType {
    get { return reqType_; }
    set {
      reqType_ = value;
    }
  }

  /// <summary>Field number for the "game_data" field.</summary>
  public const int GameDataFieldNumber = 4;
  private string gameData_ = "";
  /// <summary>
  //// 序列化的游戏数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameData {
    get { return gameData_; }
    set {
      gameData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SendGameBst);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SendGameBst other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ReqType != other.ReqType) return false;
    if (GameData != other.GameData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ReqType != 0) hash ^= ReqType.GetHashCode();
    if (GameData.Length != 0) hash ^= GameData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ReqType != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ReqType);
    }
    if (GameData.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ReqType != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ReqType);
    }
    if (GameData.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ReqType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReqType);
    }
    if (GameData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SendGameBst other) {
    if (other == null) {
      return;
    }
    if (other.ReqType != 0) {
      ReqType = other.ReqType;
    }
    if (other.GameData.Length != 0) {
      GameData = other.GameData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 24: {
          ReqType = input.ReadInt32();
          break;
        }
        case 34: {
          GameData = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 24: {
          ReqType = input.ReadInt32();
          break;
        }
        case 34: {
          GameData = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
